name: opentrivia_flutter
description: demo di opentrivia
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  http: ^1.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_database: ^10.4.0
  cloud_firestore: ^4.14.0
  firebase_ui_auth: ^1.0.5
  firebase_ui_oauth: ^1.0.5
  firebase_ui_oauth_google: ^1.0.5
  google_sign_in: ^6.2.1
  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: ^8.0.6
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.7.1
  analyzer: ^6.2.0

flutter:
  assets:
    - assets/images/


false_secrets:
  - "/example/**/google-services.json"
  - "/example/**/firebase_options.dart"
  - "/example/**/GoogleService-Info.plist"

